version: 2.1
jobs:
  build:
    resource_class: arm.medium
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=main-arm64
            SHA=$(git rev-parse HEAD)
            SHORTSHA="${SHA:0:7}"
            SHA_TAG=sha-$SHORTSHA-arm64
            echo $GHCR_PASSWORD | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_udp:$TAG --target udp -f docker/rasta_grpc_bridge/Dockerfile .
            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tcp:$TAG --target tcp -f docker/rasta_grpc_bridge/Dockerfile .
            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_dtls:$TAG --target dtls -f docker/rasta_grpc_bridge/Dockerfile .
            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tls:$TAG --target tls -f docker/rasta_grpc_bridge/Dockerfile .

            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_udp:$SHA_TAG --target udp -f docker/rasta_grpc_bridge/Dockerfile .
            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tcp:$SHA_TAG --target tcp -f docker/rasta_grpc_bridge/Dockerfile .
            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_dtls:$SHA_TAG --target dtls -f docker/rasta_grpc_bridge/Dockerfile .
            docker buildx build --platform linux/arm64 -t ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tls:$SHA_TAG --target tls -f docker/rasta_grpc_bridge/Dockerfile .

            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_udp:$TAG
            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tcp:$TAG
            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_dtls:$TAG
            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tls:$TAG

            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_udp:$SHA_TAG
            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tcp:$SHA_TAG
            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_dtls:$SHA_TAG
            docker push ghcr.io/eulynx-live/librasta/rasta_grpc_bridge_tls:$SHA_TAG
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
