version: 2.1
jobs:
  build:
    resource_class: arm.medium
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build and Push application Docker image
          command: |
            docker build -t librasta/rasta_grpc_bridge_udp:latest --target udp -f docker/rasta_grpc_bridge/Dockerfile .
